# Generated by Django 4.1.7 on 2023-02-27 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConverationMessage',
            new_name='ConversationMessage',
        ),
    ]
